# Generated by Django 2.2.5 on 2019-09-08 04:39

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190908_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='filename',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='file',
            field=models.FileField(upload_to=app.models.file_path),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
